
version: 2

models:
  - name: your_model_name_here  # Replace this with the name of your dbt model
    description: "Description of what this model represents."
    columns:
      - name: AIRLINE
        description: "The airline code."
        tests:
          - unique
          - not_null

      - name: FLIGHTCONNECTION
        description: "The flight connection number."
        tests:
          - unique
          - not_null

      - name: FLIGHTDATE
        description: "The date of the flight."
        tests:
          - not_null

      - name: BOOKNUMBER
        description: "The booking number."
        tests:
          - unique
          - not_null

      - name: CUSTOMER
        description: "Unique identifier for a customer."
        tests:
          - not_null

      - name: TRAVELAGENCY
        description: "The travel agency involved."
        tests:
          - not_null

      - name: CALENDARYEAR
        description: "The year in which the flight is booked."
        tests:
          - not_null

      - name: CALENDARMONTH
        description: "The month in which the flight is booked."
        tests:
          - not_null

      - name: CUSTOMERCOUNTRY
        description: "The country of the customer."
        tests:
          - not_null

      - name: CUSTOMERCITY
        description: "The city of the customer."
        tests:
          - not_null

      - name: WEIGHTOFLUGGAGE
        description: "The weight of the luggage."
        tests:
          - not_null

      - name: WEIGHTUOM
        description: "Unit of measure for luggage weight."
        tests:
          - not_null

      - name: BOOKINGPRICE
        description: "The price of the booking."
        tests:
          - not_null

      - name: CURRENCY
        description: "The currency of the booking."
        tests:
          - not_null

      - name: DBX_TIMESTAMP
        description: "Timestamp for the record."
        tests:
          - not_null

      - name: DBX_SEQUENCE_NUMBER
        description: "Sequence number for ordering."
        tests:
          - unique
          - not_null

